//#include "/Users/tuos/Dropbox/RUN2015/rpPb/pPbSpectra/hin12017/plotStyle/vandyStyle.h"
//#include "TDatime.h"
//void muVStime()
{
   const int nLM=3000;
   const int nL[6]={1002, 329, 389, 1613, 2132, 952};
   int time[6][nLM];
   double tmpd;
   int tmpi;
   double xtime[6][nLM];
   double mu[6][nLM];
   TDatime *da[nLM];

   ifstream infile;
   infile.open("readyFill4634.txt");
   for(int i=0; i<nL[0]; i++)
   {
     infile>>tmpi>>tmpi>>tmpi>>time[0][i]>>time[1][i]>>time[2][i]>>time[3][i]>>time[4][i]>>time[5][i]>>tmpd>>mu[0][i]>>tmpd;
     da[i] = new TDatime(time[0][i],time[1][i],time[2][i],time[3][i],time[4][i],time[5][i]);
     xtime[0][i] = da[i]->Convert(); 
   }
   infile.close();
   infile.open("readyFill4638.txt");
   for(int i=0; i<nL[1]; i++)
   {
     infile>>tmpi>>tmpi>>tmpi>>time[0][i]>>time[1][i]>>time[2][i]>>time[3][i]>>time[4][i]>>time[5][i]>>tmpd>>mu[1][i]>>tmpd;
     da[i] = new TDatime(time[0][i],time[1][i],time[2][i],time[3][i],time[4][i],time[5][i]);
     xtime[1][i] = da[i]->Convert();
   }
   infile.close();
   infile.open("readyFill4639.txt");
   for(int i=0; i<nL[2]; i++)
   {
     infile>>tmpi>>tmpi>>tmpi>>time[0][i]>>time[1][i]>>time[2][i]>>time[3][i]>>time[4][i]>>time[5][i]>>tmpd>>mu[2][i]>>tmpd;
     da[i] = new TDatime(time[0][i],time[1][i],time[2][i],time[3][i],time[4][i],time[5][i]);
     xtime[2][i] = da[i]->Convert();
   }
   infile.close();
   infile.open("readyFill4640.txt");
   for(int i=0; i<nL[3]; i++)
   {
     infile>>tmpi>>tmpi>>tmpi>>time[0][i]>>time[1][i]>>time[2][i]>>time[3][i]>>time[4][i]>>time[5][i]>>tmpd>>mu[3][i]>>tmpd;
     da[i] = new TDatime(time[0][i],time[1][i],time[2][i],time[3][i],time[4][i],time[5][i]);
     xtime[3][i] = da[i]->Convert();
   }
   infile.close();
   infile.open("readyFill4643.txt");
   for(int i=0; i<nL[4]; i++)
   {
     infile>>tmpi>>tmpi>>tmpi>>time[0][i]>>time[1][i]>>time[2][i]>>time[3][i]>>time[4][i]>>time[5][i]>>tmpd>>mu[4][i]>>tmpd;
     da[i] = new TDatime(time[0][i],time[1][i],time[2][i],time[3][i],time[4][i],time[5][i]);
     xtime[4][i] = da[i]->Convert();
   }
   infile.close();
   infile.open("readyFill4647.txt");
   for(int i=0; i<nL[5]; i++)
   {
     infile>>tmpi>>tmpi>>tmpi>>time[0][i]>>time[1][i]>>time[2][i]>>time[3][i]>>time[4][i]>>time[5][i]>>tmpd>>mu[5][i]>>tmpd;
     da[i] = new TDatime(time[0][i],time[1][i],time[2][i],time[3][i],time[4][i],time[5][i]);
     xtime[5][i] = da[i]->Convert();
   }
   infile.close();

   //TDatime da5(2008,02,28,19,56,00);
   //x[4] = da5.Convert();

  TCanvas* c1 = new TCanvas("c1","",900,600);
  c1->SetLeftMargin(0.12);
  c1->SetRightMargin(0.01);
  c1->SetTopMargin(0.01);
  c1->SetBottomMargin(0.12);
  c1->SetTicks(1);
  c1->SetGridx(1);
  c1->SetGridy(1);
  //c1->SetLogy();
  c1->Divide(3,2);
  gStyle->SetOptStat(0);
  c1->cd(1);
  double right=0.02;
  double top=0.02;
  double bottom=0.12;
  double left=0.12;
   gPad->SetTopMargin(top);
   gPad->SetBottomMargin(bottom);
   gPad->SetLeftMargin(left);
   gPad->SetRightMargin(right);
   gPad->SetTicks(1);
   TGraph mgr(nL[0],xtime[0],mu[0]);
   mgr.SetTitle("");
   mgr.SetMarkerStyle(24);
   mgr.SetMarkerColor(2);
   mgr.Draw("ap");
   mgr.GetXaxis()->SetTimeDisplay(1);
   mgr.GetXaxis()->SetNdivisions(-502);
   //mgr.GetXaxis()->SetTimeFormat("%Y-%m-%d %H:%M");
   mgr.GetXaxis()->SetTimeFormat("%Y-%m-%d");
   mgr.GetXaxis()->SetTimeOffset(0,"gmt");
   mgr.GetYaxis()->SetTitle("Average Pileup (#mu)");
   mgr.GetYaxis()->SetTitleOffset(1.06);
   mgr.GetYaxis()->SetTitleSize(0.056);
   mgr.GetYaxis()->SetTitleFont(62);
   mgr.GetYaxis()->CenterTitle(1);
   mgr.GetXaxis()->SetLabelOffset(0.05);
   mgr.GetXaxis()->SetLabelFont(62);
   mgr.GetXaxis()->SetLabelSize(0.056);
    TLatex *tex1= new TLatex(xtime[0][0]+(xtime[0][660]-xtime[0][0])/1.15,0.465,"Fill 4634");
    tex1->SetTextColor(1);
    tex1->SetTextSize(0.05);
    tex1->SetTextFont(62);
    tex1->Draw();
    TLine *line1 = new TLine(xtime[0][233],0,xtime[0][233],0.5);
    line1->SetLineStyle(2);
    line1->SetLineWidth(2);
    //line1->Draw();
   TBox *box = new TBox(xtime[0][0],0.0,xtime[0][233],0.26);
   box->SetFillColor(1);
   box->SetFillStyle(3001);
   box->SetLineColor(1);
   box->SetLineStyle(0);
   box->SetLineWidth(2);
   box->Draw();
   TBox *box = new TBox(xtime[0][234],0.0,xtime[0][365],0.26);
   box->SetFillColor(2);
   box->SetFillStyle(3001);
   box->SetLineColor(2);
   box->SetLineStyle(0);
   box->SetLineWidth(2);
   box->Draw();
   TBox *box = new TBox(xtime[0][366],0.0,xtime[0][643],0.26);
   box->SetFillColor(4);
   box->SetFillStyle(3001);
   box->SetLineColor(4);
   box->SetLineStyle(0);
   box->SetLineWidth(2);
   box->Draw();
   TBox *box = new TBox(xtime[0][644],0.0,xtime[0][829],0.26);
   box->SetFillColor(6);
   box->SetFillStyle(3001);
   box->SetLineColor(6);
   box->SetLineStyle(0);
   box->SetLineWidth(2);
   box->Draw();
   TBox *box = new TBox(xtime[0][830],0.0,xtime[0][1001],0.26);
   box->SetFillColor(8);
   box->SetFillStyle(3001);
   box->SetLineColor(8);
   box->SetLineStyle(0);
   box->SetLineWidth(2);
   box->Draw();
  c1->cd(2);
   gPad->SetTopMargin(top);
   gPad->SetBottomMargin(bottom);
   gPad->SetLeftMargin(left);
   gPad->SetRightMargin(right);
   gPad->SetTicks(1);
   TGraph mgr2(nL[1],xtime[1],mu[1]);
   mgr2.SetTitle("");
   mgr2.SetMarkerStyle(24);
   mgr2.SetMarkerColor(2);
   mgr2.Draw("ap");
   mgr2.GetXaxis()->SetTimeDisplay(1);
   mgr2.GetXaxis()->SetNdivisions(-502);
   mgr2.GetXaxis()->SetTimeFormat("%Y-%m-%d");
   mgr2.GetXaxis()->SetTimeOffset(0,"gmt");
   mgr2.GetYaxis()->SetTitle("Average Pileup (#mu)");
   mgr2.GetYaxis()->SetTitleOffset(1.06);
   mgr2.GetYaxis()->SetTitleSize(0.056);
   mgr2.GetYaxis()->SetTitleFont(62);
   mgr2.GetYaxis()->CenterTitle(1);
   mgr2.GetXaxis()->SetLabelOffset(0.05);
   mgr2.GetXaxis()->SetLabelFont(62);
   mgr2.GetXaxis()->SetLabelSize(0.056);
    TLatex *tex1= new TLatex(xtime[1][0]+(xtime[1][100]-xtime[1][0])/0.44,1.15,"Fill 4638");
    tex1->SetTextColor(1);
    tex1->SetTextSize(0.05);
    tex1->SetTextFont(62);
    tex1->Draw();
   TBox *box = new TBox(xtime[1][0],0.0,xtime[1][47],0.65);
   box->SetFillColor(1);
   box->SetFillStyle(3001);
   box->SetLineColor(1);
   box->SetLineStyle(0);
   box->SetLineWidth(2);
   box->Draw();
   TBox *box = new TBox(xtime[1][48],0.0,xtime[1][328],0.65);
   box->SetFillColor(2);
   box->SetFillStyle(3001);
   box->SetLineColor(2);
   box->SetLineStyle(0);
   box->SetLineWidth(2);
   box->Draw();
  c1->cd(3);
   gPad->SetTopMargin(top);
   gPad->SetBottomMargin(bottom);
   gPad->SetLeftMargin(left);
   gPad->SetRightMargin(right);
   gPad->SetTicks(1);
   TGraph mgr3(nL[2],xtime[2],mu[2]);
   mgr3.SetTitle("");
   mgr3.SetMarkerStyle(24);
   mgr3.SetMarkerColor(2);
   mgr3.Draw("ap");
   mgr3.GetXaxis()->SetTimeDisplay(1);
   mgr3.GetXaxis()->SetNdivisions(-502);
   mgr3.GetXaxis()->SetTimeFormat("%Y-%m-%d");
   mgr3.GetXaxis()->SetTimeOffset(0,"gmt");
   mgr3.GetYaxis()->SetTitle("Average Pileup (#mu)");
   mgr3.GetYaxis()->SetTitleOffset(1.06);
   mgr3.GetYaxis()->SetTitleSize(0.056);
   mgr3.GetYaxis()->SetTitleFont(62);
   mgr3.GetYaxis()->CenterTitle(1);
   mgr3.GetXaxis()->SetLabelOffset(0.05);
   mgr3.GetXaxis()->SetLabelFont(62);
   mgr3.GetXaxis()->SetLabelSize(0.056);
    TLatex *tex1= new TLatex(xtime[2][0]+(xtime[2][100]-xtime[2][0])/0.35,1.115,"Fill 4639");
    tex1->SetTextColor(1);
    tex1->SetTextSize(0.05);
    tex1->SetTextFont(62);
    tex1->Draw();
   TBox *box = new TBox(xtime[2][0],0.0,xtime[2][388],0.62);
   box->SetFillColor(1);
   box->SetFillStyle(3001);
   box->SetLineColor(1);
   box->SetLineStyle(0);
   box->SetLineWidth(2);
   box->Draw();
  c1->cd(4);
   gPad->SetTopMargin(top);
   gPad->SetBottomMargin(bottom);
   gPad->SetLeftMargin(left);
   gPad->SetRightMargin(right);
   gPad->SetTicks(1);
   TGraph mgr4(nL[3],xtime[3],mu[3]);
   mgr4.SetTitle("");
   mgr4.SetMarkerStyle(24);
   mgr4.SetMarkerColor(2);
   mgr4.Draw("ap");
   mgr4.GetXaxis()->SetTimeDisplay(1);
   mgr4.GetXaxis()->SetNdivisions(-502);
   mgr4.GetXaxis()->SetTimeFormat("%Y-%m-%d");
   mgr4.GetXaxis()->SetTimeOffset(0,"gmt");
   mgr4.GetYaxis()->SetTitle("Average Pileup (#mu)");
   mgr4.GetYaxis()->SetTitleOffset(1.06);
   mgr4.GetYaxis()->SetTitleSize(0.056);
   mgr4.GetYaxis()->SetTitleFont(62);
   mgr4.GetYaxis()->CenterTitle(1);
   mgr4.GetXaxis()->SetLabelOffset(0.05);
   mgr4.GetXaxis()->SetLabelFont(62);
   mgr4.GetXaxis()->SetLabelSize(0.056);
    TLatex *tex1= new TLatex(xtime[3][0]+(xtime[3][100]-xtime[3][0])/0.1345,1.116,"Fill 4640");
    tex1->SetTextColor(1);
    tex1->SetTextSize(0.05);
    tex1->SetTextFont(62);
    tex1->Draw();
   TBox *box = new TBox(xtime[3][0],0.0,xtime[3][27],0.4);
   box->SetFillColor(1);
   box->SetFillStyle(3001);
   box->SetLineColor(1);
   box->SetLineStyle(0);
   box->SetLineWidth(2);
   box->Draw();
   TBox *box = new TBox(xtime[3][28],0.0,xtime[3][119],0.4);
   box->SetFillColor(2);
   box->SetFillStyle(3001);
   box->SetLineColor(2);
   box->SetLineStyle(0);
   box->SetLineWidth(2);
   box->Draw();
   TBox *box = new TBox(xtime[3][120],0.0,xtime[3][354],0.4);
   box->SetFillColor(4);
   box->SetFillStyle(3001);
   box->SetLineColor(4);
   box->SetLineStyle(0);
   box->SetLineWidth(2);
   box->Draw();
   TBox *box = new TBox(xtime[3][355],0.0,xtime[3][511],0.4);
   box->SetFillColor(6);
   box->SetFillStyle(3001);
   box->SetLineColor(6);
   box->SetLineStyle(0);
   box->SetLineWidth(2);
   box->Draw();
   TBox *box = new TBox(xtime[3][512],0.0,xtime[3][1612],0.4);
   box->SetFillColor(8);
   box->SetFillStyle(3001);
   box->SetLineColor(8);
   box->SetLineStyle(0);
   box->SetLineWidth(2);
   box->Draw();
  c1->cd(5);
   gPad->SetTopMargin(top);
   gPad->SetBottomMargin(bottom);
   gPad->SetLeftMargin(left);
   gPad->SetRightMargin(right);
   gPad->SetTicks(1);
   TGraph mgr5(nL[4],xtime[4],mu[4]);
   mgr5.SetTitle("");
   mgr5.SetMarkerStyle(24);
   mgr5.SetMarkerColor(2);
   mgr5.Draw("ap");
   mgr5.GetXaxis()->SetTimeDisplay(1);
   mgr5.GetXaxis()->SetNdivisions(-502);
   mgr5.GetXaxis()->SetTimeFormat("%Y-%m-%d");
   mgr5.GetXaxis()->SetTimeOffset(0,"gmt");
   mgr5.GetYaxis()->SetTitle("Average Pileup (#mu)");
   mgr5.GetYaxis()->SetTitleOffset(1.06);
   mgr5.GetYaxis()->SetTitleSize(0.056);
   mgr5.GetYaxis()->SetTitleFont(62);
   mgr5.GetYaxis()->CenterTitle(1);
   mgr5.GetXaxis()->SetLabelOffset(0.05);
   mgr5.GetXaxis()->SetLabelFont(62);
   mgr5.GetXaxis()->SetLabelSize(0.056);
    TLatex *tex1= new TLatex(xtime[4][0]+(xtime[4][100]-xtime[4][0])/0.069,1.14,"Fill 4643");
    tex1->SetTextColor(1);
    tex1->SetTextSize(0.05);
    tex1->SetTextFont(62);
    tex1->Draw();
   TBox *box = new TBox(xtime[4][0],0.0,xtime[4][80],0.415);
   box->SetFillColor(1);
   box->SetFillStyle(3001);
   box->SetLineColor(1);
   box->SetLineStyle(0);
   box->SetLineWidth(2);
   box->Draw();
   TBox *box = new TBox(xtime[4][81],0.0,xtime[4][423],0.415);
   box->SetFillColor(2);
   box->SetFillStyle(3001);
   box->SetLineColor(2);
   box->SetLineStyle(0);
   box->SetLineWidth(2);
   box->Draw();
   TBox *box = new TBox(xtime[4][424],0.0,xtime[4][656],0.415);
   box->SetFillColor(4);
   box->SetFillStyle(3001);
   box->SetLineColor(4);
   box->SetLineStyle(0);
   box->SetLineWidth(2);
   box->Draw();
   TBox *box = new TBox(xtime[4][657],0.0,xtime[4][734],0.415);
   box->SetFillColor(6);
   box->SetFillStyle(3001);
   box->SetLineColor(6);
   box->SetLineStyle(0);
   box->SetLineWidth(2);
   box->Draw();
   TBox *box = new TBox(xtime[4][735],0.0,xtime[4][1748],0.415);
   box->SetFillColor(8);
   box->SetFillStyle(3001);
   box->SetLineColor(8);
   box->SetLineStyle(0);
   box->SetLineWidth(2);
   box->Draw();
   TBox *box = new TBox(xtime[4][1749],0.0,xtime[4][1827],0.415);
   box->SetFillColor(1);
   box->SetFillStyle(3001);
   box->SetLineColor(1);
   box->SetLineStyle(0);
   box->SetLineWidth(2);
   box->Draw();
   TBox *box = new TBox(xtime[4][1828],0.0,xtime[4][2131],0.415);
   box->SetFillColor(2);
   box->SetFillStyle(3001);
   box->SetLineColor(2);
   box->SetLineStyle(0);
   box->SetLineWidth(2);
   box->Draw();
  c1->cd(6);
   gPad->SetTopMargin(top);
   gPad->SetBottomMargin(bottom);
   gPad->SetLeftMargin(left);
   gPad->SetRightMargin(right);
   gPad->SetTicks(1);
   TGraph mgr6(nL[5],xtime[5],mu[5]);
   mgr6.SetTitle("");
   mgr6.SetMarkerStyle(24);
   mgr6.SetMarkerColor(2);
   mgr6.Draw("ap");
   mgr6.GetXaxis()->SetTimeDisplay(1);
   mgr6.GetXaxis()->SetNdivisions(-502);
   mgr6.GetXaxis()->SetTimeFormat("%Y-%m-%d");
   mgr6.GetXaxis()->SetTimeOffset(0,"gmt");
   mgr6.GetYaxis()->SetTitle("Average Pileup (#mu)");
   mgr6.GetYaxis()->SetTitleOffset(1.06);
   mgr6.GetYaxis()->SetTitleSize(0.056);
   mgr6.GetYaxis()->SetTitleFont(62);
   mgr6.GetYaxis()->CenterTitle(1);
   mgr6.GetXaxis()->SetLabelOffset(0.05);
   mgr6.GetXaxis()->SetLabelFont(62);
   mgr6.GetXaxis()->SetLabelSize(0.056);
    TLatex *tex1= new TLatex(xtime[5][0]+(xtime[5][100]-xtime[5][0])/0.14,1.04,"Fill 4647");
    tex1->SetTextColor(1);
    tex1->SetTextSize(0.05);
    tex1->SetTextFont(62);
    tex1->Draw();
   TBox *box = new TBox(xtime[5][0],0.0,xtime[5][459],0.388);
   box->SetFillColor(1);
   box->SetFillStyle(3001);
   box->SetLineColor(1);
   box->SetLineStyle(0);
   box->SetLineWidth(2);
   box->Draw();
   TBox *box = new TBox(xtime[5][460],0.0,xtime[5][538],0.388);
   box->SetFillColor(2);
   box->SetFillStyle(3001);
   box->SetLineColor(2);
   box->SetLineStyle(0);
   box->SetLineWidth(2);
   box->Draw();
   TBox *box = new TBox(xtime[5][539],0.0,xtime[5][771],0.388);
   box->SetFillColor(4);
   box->SetFillStyle(3001);
   box->SetLineColor(4);
   box->SetLineStyle(0);
   box->SetLineWidth(2);
   box->Draw();
   TBox *box = new TBox(xtime[5][772],0.0,xtime[5][951],0.388);
   box->SetFillColor(6);
   box->SetFillStyle(3001);
   box->SetLineColor(6);
   box->SetLineStyle(0);
   box->SetLineWidth(2);
   box->Draw();
/*
  TGraph *gr[6];
  for(int i=0; i<6; i++){
    gr[i] = new TGraph(nL[i],xtime[i],mu[i]);
    gr[i]->SetMarkerStyle(20);
  }
*/
/*
  //TCanvas* c1 = makeMultiCanvas("c1","c1",3,2);
  //TH1D *htemp = makeHist("htemp", "", "p_{T} (GeV/c)", "Yield", 200, 0.3, 150, kBlack);
  //htemp->SetAxisRange(0,1.5,"Y");
  //fixedFontHist1D(htemp, 2.5, 2.5);
  TCanvas* c1 = new TCanvas("c1","",900,600);
  c1->SetLeftMargin(0.12);
  c1->SetRightMargin(0.02);
  c1->SetTopMargin(0.02);
  c1->SetBottomMargin(0.12);
  c1->SetTicks(1);
  c1->SetGridx(1);
  c1->SetGridy(1);
  //c1->SetLogy();
  c1->Divide(3,2);
  gStyle->SetOptStat(0);
  c1->cd(1);  
  //SetHistStyle();
  //htemp->Draw();
 // gr[0]->Draw("ap");
 */

c1->SaveAs("plot_pilupData_L1_MinimumBiasHF2_OR_AllFills6panels.png");

}
